# Note: remember to `git submodule update --recursive` to pull in dependencies
[profile.default]
src='packages/mangrove-solidity/contracts'
test='packages/mangrove-solidity/foundry_test'
out='packages/mangrove-solidity/foundry_out'
libs=['packages/mangrove-solidity/foundry_lib']
cache_path='packages/mangrove-solidity/foundry_cache'
solc_version="0.8.14"
[profile.polygon]
eth_rpc_url="https://polygon-rpc.com"
fork_block_number=26416000
# The remappings are in remappings.txt so vscode solidity ext. can read them
# The first lines are the manual remappings
# The other lines are a copy/paste of the inferred mappings shown by `forge config` (inferred from imported libs)
# You should update remappings.txt whenever a lib change impacts remappings