name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master, feature/**, issue/**, dev-solidity, dev ]
    paths-ignore: 
      - '**.md'
  pull_request_target:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled]
    paths-ignore: 
      - '**.md'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  # Ternary-esque expression hack: The first line is the condition,
  # the 2nd line is the value if `true`, the 3rd line is the value if `false`.
  GIT_REF_TO_TEST: >
                   ${{  (   github.event_name != 'pull_request_target'
                         && github.ref )
                      || format('refs/pull/{0}/merge', github.event.number) }}
  NOTIFY_SLACK_FOR_THIS_WORKFLOW_RUN: ${{ github.ref_name == 'master' && github.event_name != 'pull_request_target' }}
jobs:
  test-warning:
    runs-on: ubuntu-latest

    steps:
    - name: Test warning
      run: |
        echo "::warning ::Review needed"
